["gcp_service_account"]
type = "service_account"
project_id = "img2txt-458311"
private_key_id = "77c76911e22519351bc43f51c5a10ae99b2b08f9"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDYJpGreDMfXqhc
banVAdk1twBtTqwBfZdOIkDAx+FLXO0st9RNk9Ee4VIOzgSmJ0Vwx/FD+BUPa+RU
wI4sZJPotpYhMWEneZ+oiiiDB31OxFE4soBF0RJP9rmYxpnKXMMZFNd/wVaCwwHa
5mdOI1+0FF7pc1XHX+QYYhE2t9raxYY5z26Tg6RdTYeF3b2WqGNfJ65RtO3qcFmU
/mzVO0A7buK4nEeghVB6MoA46bePEBvicHprt79Ce1wX83ws1dIgoBVWxkm2bcej
X4KHBT/SX6lYEt8zEgu82IFll1nKXxcan6PirAOC10odlzL6ZGWOjh4X9F11p7bx
deFtjhAxAgMBAAECggEAOFAED3onR3rvvfTMFDSBFF9y+wdOBK1lp/OAjzkD1xCE
sevKodNq3fKx4C2IRIliq/lLP/v38KaZPANWhvZFGpHHFyq4NwKWt+AWodxnpwe6
aV0H0iif7rlGrSjAlFoKchRd+Gi0Uyje6Nqx+0d3/YB5IbTsmh6/XCLgfTL1D51/
oJf6IoNX+yiMbKpZJ0INvQRg6QstwLOEzY5vIUw29sMhKjXUVO+iZvO0QP03AHJE
XNLOqv9zFWAhb0jRbG252X54hkKtf09YQ5tbOZ+yh/4M6zcDC2qbHaq4oOdM1swL
av9YkuCLtJ4CMmkqtedrdc5nnmmoq3FBE9UJKzRpCQKBgQD2fFsS2DlsKo6uzoAn
vrZJ3ACm9+7C3tubj/EF/lX8Fdq1bHfhxnGZU2ak2+WA4nJoJL+AZ32McNMQpo+F
9++CDURE8zaiYM18itDeZ6GDVVUI48HswctOM7hyvzefqkPAN+MUFJ+Z1IhSFhUO
o17UJ3kSmAyBAJCp4qnk+ArApwKBgQDgfnUgh5mWh7iV4wPlhnPec54MdQfyq9fU
tDBENVW2xdvJikpiJueN6RTMJkSYlli4OQLCVVc5jb+VIUqFpXQ81ekF56qV8S/J
v0qO0StbsdcQtQeI4aSumRSwC9JIHOo3n50r8ca+d45ozfj+euoUTtrJ4CUrKDRH
2KNtt32rZwKBgBFq0iivvMcG7tQtZWLpmAn6ENW7mVSN2OjSMA7jXQIWLUE6q/H5
StexzAQEQeBsn/b5+cpCBd4hrthzXJrz3SnMdDGHGio5Ouv9BytgGUqlgf/B0FdB
jnM1NmhtWKngpy7zBAnMN0bwfL2IL+673pyROX313pRTDOXkTWsPl/rrAoGBAN7I
4FfN+f/G5Mnqpl1LlwV1260lHyQWoXQ29YdbHprps/pIQRUy4qyUWM1YVM7QtW7t
NO3CX3OAVlYa2afT0IznA/+WLlXrKq+eJNGihtLSpEmyPa37r8CNrlgfAyoJd+6H
eiS4JbGzWCJt9eIl/NL2hm29AWXY2jlKprUlWZOVAoGADruaiIOeppIfp95iyvno
0msz2LXpe+vHf2cnfXISA20BMCHckh7H3Q1wjF1X+t8CvFE5lV8I63TR5oLmfiCU
g+05A0WXEN6z8sZfjY9meCnVmjB5kwbe8FrcBHUC/qrVikLbJm9657IXUBR4sQrf
pscdxtmsU2zngjzXGiAivDI=
-----END PRIVATE KEY-----"""
client_email = "easydrafting@img2txt-458311.iam.gserviceaccount.com"
client_id = "117350840124651403550"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/easydrafting%40img2txt-458311.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
